version: "3.8"
services:

 db:
  image: postgres:13.1-alpine
  environment:
   - POSTGRES_PASSWORD=password
  ports:
   - 5432:5432
  volumes:
   - ./server/db_script/changd.sql:/docker-entrypoint-initdb.d/changd.sql
  restart: always

 api:
  depends_on:
   - db
  build:
   context: ./server
   dockerfile: Dockerfile

  ports:
   - 8000:8000
  volumes:
   - /app/node_modules

 ui_server:
  depends_on:
   - api
  image: nginx:1.19.4-alpine
  ports:
   - 80:80
  volumes:
   - ./frontend/build:/usr/share/nginx/html
   - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf