version: "3.8"
services:

 db:
  image: postgres:13.1-alpine
  environment:
   - POSTGRES_PASSWORD=password
  ports:
   - 5432:5432
  volumes:
   - ./server/db_script/changd.sql:/docker-entrypoint-initdb.d/changd.sql
  restart: always

 api:
  depends_on:
   - db
  build:
   context: ./server
   dockerfile: Dockerfile
  environment:
   - NODE_ENV=prod

   # Postgres DB Connection Parameters
   - DB_HOST=db
   - DB_NAME=postgres
   - DB_PORT=5432
   - DB_USERNAME=postgres
   - DB_PASSWORD=password
   - DB_SCHEMA=public

   # Node/Express API Port
   - API_PORT=8000
   - TOKEN_SECRET=myappsecret

   # Image comparison options
   - PIXELMATCH_PROCESSING_THRESHOLD=0.0
   - PIXELMATCH_OUTPUT_ALPHA=0.6
   - CAPTURE_IMAGE_HEIGHT=5000
   - CAPTURE_IMAGE_WIDTH=1024

   # Option for saving screenshots locally or to AWS S3
   - FILESYSTEM=LOCAL
   - DOMAIN=api
   
   # Required if FILESYSTEM=S3
   - S3_BUCKET=
   - AWS_ACCESS_KEY_ID=
   - AWS_SECRET_ACCESS_KEY=
  
   # Mail Notification Options
   - MAILSYSTEM=SMTP #SMTP or SES
   - EMAIL_FROM=myemail@email.com

   # Required if MAILSYSTEM=S3
   - SES_ACCESS_KEY=
   - SES_ACCESS_SECRET=

   # Required if MAILSYSTEM=SMTP
   - SMTP_HOST=smtp.mailgun.org
   - SMTP_PORT=587
   - SMTP_USER=
   - SMTP_PASSWORD=

  ports:
   - 8000:8000
  volumes:
   - /app/node_modules

 ui_server:
  depends_on:
   - api
  image: nginx:1.19.4-alpine
  ports:
   - 80:80
  volumes:
   - ./frontend/build:/usr/share/nginx/html
   - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf